Shopify/measured

.gitignore
Gemfile
LICENSE
README.md
Rakefile
lib/measured.rb
lib/measured/arithmetic.rb
lib/measured/base.rb
lib/measured/conversion.rb
lib/measured/conversion_table.rb
lib/measured/measurable.rb
lib/measured/unit.rb
lib/measured/units/length.rb
lib/measured/units/weight.rb
lib/measured/version.rb
measured.gemspec
test/arithmetic_test.rb
test/conversion_table_test.rb
test/conversion_test.rb
test/measurable_test.rb
test/support/fake_system.rb
test/test_helper.rb
test/unit_error_test.rb
test/unit_test.rb
test/units/length_test.rb
test/units/weight_test.rb

@Shopify/shipping @maartenvg @celsodantas @boourns @jnormore 
This is version 0.0.1 of a library I have written to encapsulate measurements, weight and dimensions to start with, in a single object.
Currently in Shopify we juggle two different properties which really define a single weight or dimension. We do lossy math with `UnitSystem` aka `Quantified` meaning our precision is bad. And we have no atomic way of reading/writing these to columns in the DB with ActiveRecord without juggling the fields by ourselves.
All math is done in this gem with `BigDecimal`. Conversions are extensible.
I wrote a detailed README. Read it. Please:
https://github.com/Shopify/measured/blob/version-0.0.1/README.md
There are two unit management libs I could find of note. They are contrasted in the README. …

Measured version 0.0.1

---

README.md
lib/measured/measurable.rb
lib/measured/version.rb
measured.gemspec
test/measurable_test.rb
test/units/length_test.rb
test/units/weight_test.rb

Adds a `valid_unit?` method to check if a unit is in the list. Needed for work in [`measured-rails`](https://github.com/Shopify/measured-rails).
At the same time:
Bumped Bundler version. Bumped this gem to 0.0.2.
Also skipped a bunch of tests. The core lib tests work, but these are tests that are checking precision of conversion. They are dependent on system architecture so CI will return different significant digits than running it on your machine. Skip them for now so CI passes. Later I'll write better cross platform tests.
Test failure examples:
```
1) Failure:
Measured::LengthTest#test_.convert_to_from_mm_to_ft [/home/travis/build/Shopify/measured/test/units/length_test.rb:122]:
--- expected
+++ actual
@@ -1 +1 @@
-#<BigDecimal:1cc8c00,'0.656167979E1',18(27)> …
```

Add a valid_unit? class method

---

lib/measured/conversion.rb
lib/measured/measurable.rb
lib/measured/version.rb
test/conversion_test.rb
test/measurable_test.rb

When converting from a `Float` to a `BigDecimal` Ruby requires the number of significant digits to be specified. This means that if we have `1.2345678` and we say two digits it knows to convert it to `BigDecimal(1.23)`.
Failing to do so raises:
```
ArgumentError: can't omit precision for a Float.
```

Required significant digits for float conversion

---

lib/measured/measurable.rb
lib/measured/version.rb
test/measurable_test.rb

If you initialized a measurement with `nil` as the value, previously it would attempt to parse it as a string internally and raise a very unclear error. 
Raise explicitly for `nil` values.

Initialize with nil

---

lib/measured/measurable.rb
lib/measured/version.rb
test/measurable_test.rb
test/units/length_test.rb
test/units/weight_test.rb

Add a helper for the name of the measurable. I want to use it for clearer validation messages in [measured-rails](https://github.com/Shopify/measured-rails). It can be easily overridden on the subclasses if needed.

Add .name helper to Measurable

---

README.md
lib/measured/measurable.rb
lib/measured/version.rb
test/measurable_test.rb

Changes implementation of comparison operators (`==`, `.eql?`, and `<=>`) to do the conversion between units. Does this only as needed.
Update the `convert_to` operator to exit early and return the measurement unchanged if the conversion is to the unit it is already in.
Example, this was false but is now true:
```ruby
> Measured::Length(1000, :cm) == Measured::Length(1, :m)
true
```

Convert as required when doing comparison between different units

---

README.md
lib/measured/measurable.rb
lib/measured/version.rb
test/measurable_test.rb

Previously, comparing a ```Measured::Measurable``` against any scalar raised an ```ArgumentError``` since it expects all arguments being compared to be of the same class. This prevented us from comparing against ```0``` which is a pretty good UX for this gem. Comparison with zeros of ```BigDecimal``` (i.e ```BigDecimal.new(0)```) and ```Float``` (i.e ```0.0```) work as expected. 
Comparing ```Measured::Measurable``` objects against other non-zero scalars still raises an error just like before.
Example:
```ruby
x = Measured::Length(2, :m)
x > 0  ## evaluates to true
x < 0.0 ## evaluates to false
x == BigDecimal.new(0) ## also false
x == 2 ## ArgumentError
```

Numerical comparison against all types of zeros should be permitted

---

measured.gemspec

**Context**
We use shipit to deploy measured to rubygems. Shipit currently pegged at bundler v1.7.3 and doesn't support v1.8 and above. 
It doesn't seem like we need bundler > 1.7.3 for this gem.
@Shopify/shipping @kmcphillips

Removing bundler from measured

---

lib/measured/conversion.rb
lib/measured/measurable.rb
test/conversion_test.rb
test/measurable_test.rb

Let's use 6 digits to round, not six significant digits, when converting floats to `BigDecimal`.
cc @kmcphillips

Round floats to six digits, not six significant digits.

---

lib/measured/measurable.rb
lib/measured/version.rb
test/measurable_test.rb

@garethson @cyprusad 
We don't cleanly handle initializations with `nil` and `""`.
Handle them explicitly with the same exceptions and clean names.
Bumps to `0.0.9`.

Handle exceptions for nil and blank more cleanly

---

lib/measured/base.rb
lib/measured/version.rb
test/measurable_test.rb

@cyprusad @garethson 
Found a `require` bug when working with @mdking. Requiring `active_support` actually doesn't include much, including many helpers that are assumed to exist:
```ruby
~/s/measured(master)$ irb
irb(main):001:0> require 'measured'
=> true
irb(main):002:0> Measured::Length.new(1, :cm)
NoMethodError: undefined method `blank?' for :cm:Symbol
from /Users/kevin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/measured-0.0.9/lib/measured/measurable.rb:8:in `initialize'
from (irb):2:in `new'
from (irb):2
from /Users/kevin/.rbenv/versions/2.1.1/bin/irb:11:in `<main>'
```

Require active_support/all correctly. Bump version 0.0.10

---

README.md
lib/measured/base.rb
lib/measured/version.rb
test/units/length_test.rb
test/units/weight_test.rb

@garethson @cyprusad @mdking 
Fixed a bit of syntax sugar that I have wanted for a while.
Similar to how you can initialize a `BigDecimal(123)` without the `.new` I have added some metaprogramming to allow that for any subclasses of `Measured` in the namespace.
```ruby
Measured::Length(1, :cm)
```

Allow initialization from module

---

lib/measured/conversion.rb
lib/measured/conversion_table.rb
lib/measured/unit.rb
lib/measured/version.rb
test/test_helper.rb
test/units/length_test.rb
test/units/weight_test.rb

Fixes #4 to some extent.
Measured builds a conversion table in `Measured::ConversionTable` but some values in the table would be wrong, for example the conversion value from feet to yards would not be `3`. The reason for this is Measured's tree traversal would go through the base unit `ft->m->yd` using `BigDecimal` for intermediate values but the `m->yd` can not be done with perfect precision with decimal numbers.
Use `Rational`s for intermediate values when building the conversion table. This means all intermediate multiplications will be done with perfect precision. Currently this fixes all the previously skipped tests.
Really this issue stems from the fact that `BigDecimal` is used at all. In a perfect world the library would only ever use `Rational` because it is always perfect and …

Use Rationals for intermediate conversion values

---

README.md
lib/measured/conversion.rb
lib/measured/measurable.rb
lib/measured/unit.rb
test/conversion_test.rb
test/unit_test.rb

Directly related to issue #3 . Implements a case_sensitive flag for each Measured::Unit instance. This flag is taken into account when checking if a unit name or alias already exists. Creates methods #name_eql? and #names_include? in Measured::Unit which allow the delegation of Measured::Conversion unit tests to each unit instance. Also adds an #add_alias method which gives the ability to add additional aliases to preexisting units.

Case sensitivity and ability to add new aliases

---

README.md
lib/measured/conversion.rb
lib/measured/measurable.rb
lib/measured/unit.rb
lib/measured/version.rb
test/conversion_test.rb
test/unit_test.rb

Sorry, @AnthonyBobsin but I am going to have to revert this for now. I should have done a better job reviewing it. But there are a couple of problems:
1) The case sensitivity should be defined at a system level. You shouldn't be able to say "centimetres are case sensitive but kilometers are not". It should be "all measurements of length are case insensitive".
2) Some of the comparison methods had no tests for `nil`/blank and were causing exceptions when I ran the tests in `measured-rails. 
I'm reverting your merge, pulled your copy changes back in, bumped to 1.1.0 as I had previously released 1.0.0, and we can work at revising your feature.
Sorry again for not being more diligent about the review and feedback.
cc @garethson

Revert case_sensitive

---

lib/measured/measurable.rb
test/measurable_test.rb

@jonathanmwatson @garethson @RichardBlair @cyprusad 
We should respond to `zero?` on `Measurable` since it doesn't matter what the unit is.
Discussion in another thread about if measured objects should respond to `to_i` and `to_f`. I think it's risky and undesirable for this reason:
```ruby
a = Measured::Length.new(1, :cm)
b = Measured::Length.new(1, :m)
a == b # false
a.to_i == b.to_i # true
```
If you really want to work with the value as an int or float, you should have to explicitly ask for the value. I believe this is correct:
```ruby
> height.to_i
NoMethodError: undefined method 'to_i' for #<Measured::Length: 1.0 cm>
from (pry):10:in '<main>'
> height.value.to_i
=> 1
```
Thoughts?

Respond to zero? through delegation

---

.travis.yml
gemfiles/activesupport-4.2.gemfile

@jonathankwok @benwah 
Update our Travis builds so that it tests with mainline rails (5.0) by default, but also with 4.2. Matrix that with the same ruby versions used to test `measured-rails`. Skip 2.1.x for rails 5 because they are incompatible.
Aligns with https://github.com/Shopify/measured-rails/pull/24

Test with consistent Ruby/Rails versions

---

lib/measured/conversion.rb
lib/measured/conversion_table.rb
test/conversion_table_test.rb

@thegedge @benwah 
Closes #38
Unnecessary to create an instance of the conversion table class to call a single function and throw it away.
Use a module function. Trade off is that we have to pass `units` down all the way through in a bunch of places.
In the 2.0 milestone, but doesn't change the interface at all for the 1.x version.

Use module function and do not instantiate table unnecessarily

---

README.md
lib/measured/measurable.rb
lib/measured/unit.rb
test/case_sensitive_measurable_test.rb
test/measurable_test.rb
test/unit_test.rb

Immutability will allow us to more easily introduce certain performance optimizations (e.g., https://github.com/Shopify/measured/pull/29), and makes these classes easier to understand and reason about.
Closes https://github.com/Shopify/measured/issues/30
Closes https://github.com/Shopify/measured/issues/37
@kmcphillips @benwah

Make Measurable and Unit immutable objects

---

measured.gemspec

@benwah @thegedge 
Closes #41
We only run tests on Rails 4.2 and up, and those are the only currently supported versions of Rails.

Explicitly support 4.2 and up only

---

lib/measured/arithmetic.rb
lib/measured/measurable.rb
test/arithmetic_test.rb

Closes https://github.com/Shopify/measured/issues/31
- Gives us some useful numerical operations (e.g., `positive?`, `abs`)
- Allows `Measurable`s to be used in any context where `Numeric` objects are expected.
@kmcphillips @jonathankwok

Have Measurable inherit from Numeric

---

README.md
lib/measured/arithmetic.rb
lib/measured/measurable.rb
test/arithmetic_test.rb
test/measurable_test.rb

As mentioned in https://github.com/Shopify/measured/issues/46, adding/subtracting `Numeric` values to/from a `Measurable` is confusing, since no unit is specified and we'd rather not assume it's in the same unit as the `Measurable`. We'd like to allow scaling the `Measurable` by a scalar, but can't do so without allowing addition too.
Given we want to avoid confusion, we'll remove the ability to coerce `Numeric` values into `Measurable`s, and require someone to manually do that conversion. This may lead to more verbose code, but hopefully things like https://github.com/Shopify/measured/issues/39 will reduce the verboseness.
In a follow up PR I'll also add a `scale` method to allow multiplying a `Measurable` by a scalar.
@kmcphillips @jonathankwok

Don't allow Numeric usage in operations

---

lib/measured/conversion.rb

From @nicolaslupien's [comment](https://github.com/Shopify/measured/pull/51#discussion_r92469298), we should suffix this function with an exclamation mark, since it raises. To keep things super tight, I've also went ahead with his suggestion to split the function. Unit tests already exist to check if `to_unit_name` and `convert` raise.

Split unit_for into a bang and non-bang version

---

README.md
lib/measured/base.rb
lib/measured/case_insensitive_unit.rb
lib/measured/conversion.rb
lib/measured/conversion_builder.rb
lib/measured/unit.rb
test/case_insensitive_unit_test.rb
test/conversion_builder_test.rb
test/conversion_test.rb
test/unit_test.rb

Right now, you have to pay some cost for case insensitive checks, even if you don't need them.
Remove this cost by creating a separate class to do `downcase`-ing. If a case-insensitive unit system is built, then this cost will be payed. If a case-sensitive unit system is built, no additional costs are paid.
Most of this PR is just a copy of `unit_test.rb`, with assertions adjusted for case insensitivity. rspec shared examples would be 👌

Separate case insensitive concerns into separate class

---

lib/measured/measurable.rb
test/arithmetic_test.rb

Ruby 2.4 unified `Fixnum` and `Bignum` under `Integer` [1], both of which were subclasses of `Integer` pre-2.4.
One small bonus of this is that a simpler `when` clause means we'll actually be faster. Here's the instructions for just `when Integer`:
```
0006 dup                                                              (   3)
0007 getinlinecache   14, <is:0>
0010 getconstant      :Integer
0012 setinlinecache   <is:0>
0014 checkmatch       2
0016 branchif         45
```
and here are the instructions for `when Fixnum, Bignum`
```
0018 dup                                                              (   5)
0019 getinlinecache   26, <is:1>
0022 getconstant      :Fixnum
0024 setinlinecache   <is:1>
0026 checkmatch       2
0028 branchif         50
0030 dup
0031 getinlinecache   38, <is:2> …
```

Replace Fixnum/Bignum with Integer

---

.travis.yml

Include Ruby 2.4.0 in our CI list. Skip Rails 4.2 as there is a JSON version conflict.
Also bump our 2.3 to 2.3.1.
Related to https://github.com/Shopify/measured-rails/pull/33

Test with ruby 2.4.0

---

README.md
lib/measured/arithmetic.rb
test/arithmetic_test.rb

From https://github.com/Shopify/measured/issues/46#issuecomment-264977606 and onwards, we want to get rid of multiplication / division on `Measurable` instances because, for example, `1kg · 1kg = 1kg²`. The new way to scale the value of a `Measurable` is via its `#scale` method.
Closes https://github.com/Shopify/measured/issues/46

Add #scale method for multiplying by a scalar

---

lib/measured/case_insensitive_conversion.rb
lib/measured/conversion.rb
lib/measured/conversion_builder.rb
lib/measured/unit.rb
test/case_insensitive_unit_test.rb
test/unit_test.rb

Simplifying the interface of `Unit`.
This is definitely up for discussion, particularly how far the case sensitivity aspects of measured dig in. A big question is was this confusing before? More specifically, would a user of our library be confused at why there's `name_eql?`, and would it have differed from `unit.name == "something"`?
In general, I'd like to drop the case-sensitive aspects of measured completely, but if we keep them I would like them to be as out of the way as possible. I think the interaction with `Unit` is rare, and in general users aren't manually comparing things but grabbing it for presentation / informational purposes.
Closes https://github.com/Shopify/measured/issues/33

Remove name_eql? and names_include? from Unit interface

---

README.md
lib/measured/conversion.rb
lib/measured/conversion_builder.rb
lib/measured/units/length.rb
lib/measured/units/weight.rb
test/case_insensitive_conversion_test.rb
test/case_insensitive_unit_test.rb
test/conversion_builder_test.rb
test/conversion_test.rb
test/measurable_test.rb
test/support/fake_system.rb
test/unit_test.rb
test/units/length_test.rb
test/units/weight_test.rb

Closes https://github.com/Shopify/measured/issues/60
The concept of a "base unit" was completely unused, so to prevent any confusion as to the importance of a base unit we'll remove it. Whenever we reference "base unit" now (in documentation / tests) we're talking about the base name for a unit (i.e., not an alias).

Remove unused concept of a "base unit"

---

lib/measured/measurable.rb
test/measurable_test.rb

Closes https://github.com/Shopify/measured/issues/35
- Removes the blank check on the unit and defers validity checks to `unit_or_alias?`
- Removes the big `case` block, deferring parsing to `BigDecimal`
Not a huge boost, about 1.1x - 1.15.x. There's still a hit for `BigDecimal`'s type checks, and we need to have a precision for floats.
__Before__
```
Warming up --------------------------------------
before    31.165k i/100ms
Calculating -------------------------------------
before    347.351k (± 4.7%) i/s -      1.745M in   5.037722s
```
__After__
```
Warming up --------------------------------------
after    33.800k i/100ms
Calculating -------------------------------------
after    385.849k (± 2.6%) i/s -      1.960M in   5.084211s
```

Simplify Measurable initializer

---

README.md
lib/measured/conversion_table.rb
lib/measured/measurable.rb
lib/measured/unit.rb
lib/measured/units/length.rb
lib/measured/units/weight.rb
test/measurable_test.rb

See https://github.com/Shopify/measured/issues/63 for more context. tl;dr `Rational` is faster for arithmetic and can represent values that `BigDecimal` cannot, but slower for parsing decimal numbers. Since the construction of units and the conversion table is a one-off operation, `Rational` is the best for representing things, especially since conversions are arithmetic operations.
Mostly takes care of https://github.com/Shopify/measured/issues/63, but I have some other changes that I want to make that'll fully close it.

Use Rational where appropriate

---

lib/measured/measurable.rb
lib/measured/unit_system.rb
test/case_insensitive_unit_system_test.rb
test/test_helper.rb
test/unit_system_test.rb

Previously we had `to_unit_name`, but this method could raise, so it should have a bang suffix.
I've resolved this by having both `to_unit_name` and `to_unit_name!`, and using the `raise`-ing nature of `to_unit_name!` to simplify `Measurable#initialize`.

Clarify the bang-ness of to_unit_name

---

lib/measured/measurable.rb
test/measurable_test.rb
test/unit_system_builder_test.rb
test/units/length_test.rb
test/units/weight_test.rb

Note: will switch to merging into master after https://github.com/Shopify/measured/pull/66 merged
It was confusing to have two sets of names for the exact same operations. To ease any future refactoring efforts and simplify the system, just delegate the names exactly as they are in `UnitSystem`.
Moved to using `%w` for lists of unit names in tests that I had to update.

Delegate names exactly to UnitSystem instead of aliasing

---

lib/measured/unit_system.rb

Since `Rational` can represent all the values that `BigDecimal` can (minus infinities), keep everything as `Rational`s and avoid the performance hit of converting things to a `BigDecimal`.

Maintain converted values as Rational instances

---

lib/measured/case_insensitive_unit.rb
lib/measured/unit.rb
test/case_insensitive_unit_test.rb
test/unit_test.rb

When comparing `foo <=> bar`, any attribute of `foo` used for comparison should generally be on the left of `<=>` for a meaningful comparison. We actually have this for one branch of `<=>` (when comparing `@name` against some non-instance of `Unit`), and should have it for the rest.
I've also followed up with adding some tests to emphasize the behaviour of the "names equal" branch, where the conversion value is used for comparison. I don't think this is the most meaningful thing for comparison, but I'll be following up with some changes that will take care of this and wanted to keep this PR leaner.

Make unit comparison behave as expected

---

lib/measured/case_insensitive_unit_system.rb
lib/measured/measurable.rb
lib/measured/unit_system.rb
test/arithmetic_test.rb
test/case_insensitive_unit_system_test.rb
test/measurable_test.rb
test/test_helper.rb
test/unit_system_builder_test.rb
test/unit_system_test.rb

Right now we're storing unit names instead of `Unit` instances in `Measurable`s, and doing a lot of unnecessary lookups for the `Unit` instances. I think it makes much more sense to store the `Unit` instance itself.
This PR is one piece in the line of changes I need to make to move towards having `Measured.build` return the unit system itself instead of a `Measurable` subclass. Additional comments in line.
Will change to merge into master once https://github.com/Shopify/measured/pull/69 merged.
About 8-10% faster.
```ruby
Benchmark.ips do |x|
x.report { Measured::Weight.new(10, :kg) + Measured::Weight.new(2, :kg) }
end
```
__Before__
```
Warming up --------------------------------------
19.306k i/100ms
Calculating -------------------------------------
209.369k (± 3.5%) i/s -      1.062M …
```

Have Measurable store unit instances instead of names

---

lib/measured/case_insensitive_unit.rb
lib/measured/measurable.rb
lib/measured/unit.rb
lib/measured/unit_system.rb
test/measurable_test.rb

It makes sense for `Unit` instances to know what system they're in. Technically, we could have units that are the same between two systems (e.g., case-sensitive and case-insensitive systems, metric/imperial, some other weird thing with magic missiles in different video games) in which case this will allow distinguishing them.
Primarily, this will simplify https://github.com/Shopify/measured/pull/71 a fair bit by removing the need to pass in a unit system to `Measurable#initialize`.

Store the unit system in Unit instances

---

test/case_insensitive_unit_system_test.rb
test/case_insensitive_unit_test.rb
test/measurable_test.rb
test/unit_system_test.rb
test/unit_test.rb

Highlights:
* Improving data used in case-insensitive tests
* Preferring `value: "x/y unit"` over `value: [Rational(x, y), :unit]` when not testing `#initialize`
* `%w`-style lists
* Not using `BigDecimal` anywhere where a `Rational` or `Integer` is fine

Tidy up and simplify unit tests

---

lib/measured/case_insensitive_unit.rb
test/case_insensitive_unit_test.rb

We `downcase` everything else, so this was a discrepancy which I would even call a bug.
The conversion unit wasn't actually used in any comparison operations, so this doesn't actually change any internal behaviour, and since `CaseInsensitiveUnit` is a concept that was introduced for 2.0, doesn't break any client of the library except those using the prereleases.

Also downcase conversion unit for CaseInsensitiveUnit

---

lib/measured/unit.rb
test/case_insensitive_unit_test.rb
test/unit_test.rb

There are units that are more than one word, so we should have an interface that allows specifying these via conversion strings in units. In other words, we should support the following:
```ruby
Length = Measured.build do
unit :m, value: "1/1852 nautical miles"
end
```

Allow multiple words for the conversion unit

---

lib/measured/unit.rb
test/case_insensitive_unit_test.rb
test/unit_test.rb

Sliced up into tiny commits that are easily digestable, but the most significant changes are:
- Values that don't change are now cached
- `#inspect` is improved, and also prints the class now (which is important, because we have `CaseInsensitiveUnit`)
- Made `#names` a method and instead expose `aliases` as an attribute

Unit improvements

---

lib/measured/measurable.rb
test/measurable_test.rb

After merging https://github.com/Shopify/measured/pull/72, `Unit#to_s` now shows its conversion when `to_s`-ing a `Measurable`. This is almost always undesirable for presentation, so we should instead just show the unit name.
Since we depend on `ActiveSupport` I've also added a `#humanize` method that can pluralize the unit name if the value isn't unity.

Only show unit name, adding #humanize for pluralization

---

measured.gemspec
test/test_helper.rb

Add `minitest-reporters` to give us cleaner output, and unsick us from an old version. We're ok with new versions, and if it breaks we should fix it.
Related to https://github.com/Shopify/measured-rails/pull/36

Add minitest reporters and update gems

---

README.md
lib/measured/base.rb
lib/measured/measurable.rb
lib/measured/parser.rb
lib/measured/unit.rb
test/measurable_test.rb
test/parser_test.rb
test/support/fake_system.rb

I'm doing some work of loading weights from files, and I want to be able to have values in an input file:
```
weight: 10.5 kg
```
And then create a weight object out of it:
```
Measured::Weight.parse("10.5 kg")
```
It's way slower than taking in the number and the symbol, but we'd be parsing those strings from the file first anyway.

Allow .parse to load from string

---

lib/measured/units/length.rb
test/units/length_test.rb

Adding support for miles and kilometers, which can be used for risk calculations.
@thegedge for review

Support miles and kilometers

---

lib/measured/units/weight.rb
test/units/weight_test.rb

Turn grams into a `si_unit` before releasing version 2.1.
Documentation and README are being updated in https://github.com/Shopify/measured/pull/92.
cc @mdking @MalazAlamir

Turn grams into si_unit

---

test/measurable_test.rb
test/unit_test.rb

Running the tests with warnings enabled (`-w` flag) reports that some expressions are ambiguous because of the lack of parenthesis and the usage of the unary operator `-`.
The output or `bundle exec rake test` / `dev test` before:
```
/Users/javierhonduco/.gem/ruby/2.3.1/gems/pry-0.11.1/lib/pry/commands/whereami.rb:196: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/javierhonduco/src/github.com/Shopify/measured/test/measurable_test.rb:240: warning: ambiguous first argument; put parentheses or a space even after `-' operator
/Users/javierhonduco/src/github.com/Shopify/measured/test/measurable_test.rb:243: warning: ambiguous first argument; put parentheses or a space even after `-' operator …
```

Fix 'ambiguous first argument' warnings in tests

---

lib/measured/measurable.rb
lib/measured/version.rb
test/measurable_test.rb

When performing string concatenations of `Measured::Weight.new(<number>, :lbs)` with a number that cannot be represented as a float, it is shown with too many decimals:
```
Measured::Weight.new(9.3, :lbs).to_s
=> "9.300000000000001 lb"
```
@benwah and I had a look of the history of the changes when we saw that [the rounding was being set to `Float::DIG + 1`](https://github.com/Shopify/measured/blob/76e7b7276b7cf435b3f7ac4402269b9a60dd9bf9/lib/measured/measurable.rb#L11-L12).
This behaviour was introduced in [this measured PR](https://github.com/Shopify/measured/pull/14), mimicking Ruby's `float#to_d` implementation behaviour.
However, with the current implementation of `Float::DIG + 1`, this is what we get:
```ruby
[2] pry(main)> BigDecimal(9.3, Float::DIG + 1).to_s
=> "9.300000000000001" …
```

Fix precision representation of floats

---

README.md
lib/measured/measurable.rb
test/measurable_test.rb

The PR adds `#format` to Measurable. Unsurprisingly, this adds a formatter to `measured` :tada:, as we discussed in #98.
Cheers!

Add formatter to Measurable closes #98

---

lib/measured/conversion_table.rb

Measured's performance when computing the conversions table could be improved. Although the hottest code path lies in the indirect conversions, while looking through the code, I spotted 2 low hanging performance gains.
1. We are computing the conversion between 2 units twice so we can have the reverse operation. We can replace the inverse operation by the mathematical inverse, the power of `-1` (which is equivalent to `1/conversion`. This makes running this code approximately twice as fast.
2. Some other minor gain comes from the `find_direct_conversion`. We check if there's any conversion from unit A to each of those possible units by checking each of those's `conversion_amount`. We then do the same but checking for the `inverse_conversion_amount`. Even though the computational …

Some low hanging performance improvements

---

lib/measured/unit.rb
test/unit_test.rb

In cases of the base unit the `conversion_amount` can validly be `nil`.
Just pass through the `nil`, and test to prevent regressions.

Guard against nil in Unit#conversion_amount

---

Rakefile

Internally at Shopify we use `dev` to run our tests. But any contributors to this gem will use `rake test` to run the tests. And this doesn't easily allow you to run just specific test files.
Add a check in the `Rakefile` allowing you to pass in a test file or many test files into `rake test test/file.rb` and run just that test.

Allow only certain test files to be run via rake test

---

lib/measured/conversion_table.rb
lib/measured/unit_system.rb
test/conversion_table_test.rb

The `Measured::ConversionTable` is built as a module where each method passes in the state. 
This is pretty unnecessary. It makes the signatures messy and it's way harder to refactor as I'm trying to do for #103.
Convert it from a module to a class. Instantiate it and call `#to_h`. No functional change, just an internal API change.

Chanage Measured::ConversionTable from a module to a class

---

lib/measured/conversion_table.rb
test/conversion_table_test.rb

Every factor in a conversion table is a `Rational` except the base one.
```
[1] pry(Measured::ConversionTable)> table
=> {"m"=>{"m"=>#<BigDecimal:561f2c7baf88,'0.1E1',9(18)>, "cm"=>(100/1), "mm"=>(1000/1)},
"cm"=>{"cm"=>#<BigDecimal:561f2c7babf0,'0.1E1',9(18)>, "m"=>(1/100), "mm"=>(10/1)},
"mm"=>{"mm"=>#<BigDecimal:561f2c7ba858,'0.1E1',9(18)>, "m"=>(1/1000), "cm"=>(1/10)}}
```
They all get coerced, but it doesn't make sense to keep it as a `BigDecimal` as the rest have been converted.
Change it to `Rational(1, 1)`.
Rewrote and improved a bunch of tests. These tests were actually coercing on comparison so they weren't type checking. Added the type checks too now.

Make the 1 to 1 factor of the conversion table be a Rational rather than BigDecimal

---

dev.yml

The current implementation doesn't allow to run multiple tests from `dev`. This PR uses #108 to do so.

Make dev test use rake test

---

test/test_helper.rb

This prevents `pry` from being loaded in the CI environment. This would have failed tests in #102 and will prevent this kind of thing from happening again. Great suggestion from @sshaw in #104.
Tested by referencing `Pry` in a test and it failed in CI:

Do not require pry in CI

---

README.md

* In the example the conversion rate is set using:
```
value: ["1.5 bu"]
```
To set a conversion rate you must pass either a [string or a
two-element array](https://github.com/Shopify/measured/blob/master/lib/measured/unit.rb#L71).
This updates the docs to use a string
```
value: "1.5 bu"
```
note how all the other units are using the string version https://github.com/Shopify/measured/tree/master/lib/measured/units

Fix Add new units README example

---

.travis.yml
gemfiles/activesupport-5.0.gemfile
gemfiles/activesupport-5.1.gemfile
measured.gemspec

This modernizes the requirements for ruby and rails for this gem. ruby >= 2.3 and rails >= 5.0.
Also adds ruby 2.6.
It matches the maintenance policies of both:
https://guides.rubyonrails.org/maintenance_policy.html
https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/
Will follow up with a version change.
Matched with https://github.com/Shopify/measured-rails/pull/53

Raise ruby requirement to 2.3 and rails to 5.0

---

README.md
test/measurable_test.rb

Fixes:
```
measurable_test.rb:301: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

Fix BigDecimal deprecations

---

lib/measured/base.rb
lib/measured/measurable.rb
lib/measured/unit.rb
lib/measured/unit_system.rb

I'm investigating memory leaks, or more exactly "durable post boot memory growth". Meaning I'm looking for objects that are allocated during a request cycle, but are held onto after the request was completed.
In this context, the profile data showed memory growth coming from `Measured::UnitSystem` and `Measured::Unit`, after a quick look it maps to the multiple uses of the memoization pattern (`@foo ||=`).
e.g:
```json
{"address":"0x56110c869930", "type":"HASH", "class":"0x5610e4f29338", "size":28, "references":["0x5610e84f9378",
```
```
harb> rootpath 0x56110c869930
root path to 0x56110c869930:
ROOT (machine_context)
0x5610e6098948 (CLASS: Rack::BodyProxy)
0x5610e4f41730 (CLASS: Object)
0x5610e85484c8 (MODULE: Measured)
0x5610e84e8640 (CLASS: Measured::Weight)
0x5610e84e84d8 (OBJECT: …
```

Reconsider most memoizations

---

.travis.yml

Replaces #129 
This removes an unnecessary gem step to fix a problem that is no longer a problem, but caused new problems.
Also supports just the mainline current ruby versions. https://www.ruby-lang.org/en/downloads/

Fix travis build and only support current ruby versions

---

lib/measured/unit.rb
lib/measured/unit_system.rb
test/unit_system_builder_test.rb

As described in #127 @trcarden, defining the value of a unit using an alias raises.
This happens because we don't have the `UnitSystem` defined yet that can look up the aliases. It's a chicken egg problem.
So we do the search manually in this case, rather than error. It's not a huge amount of effort, with a little duplication.
I've refactored the `with(` method to maintain immutability of `Unit`.

Allow unit values to be defined as aliases and not only the base unit

---

measured.gemspec
test/test_helper.rb

Fixes a small deprecation in Mocha:
```
Mocha deprecation warning at /Users/kevin/source/measured/test/test_helper.rb:6:in `require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
```
Set minimum version of Mocha where this file is supported to `1.4.0`:
https://github.com/freerange/mocha/blob/master/RELEASE.md#140

Update minitest loader for mocha to remove deprecation

---

README.md

As of this commit, the last update was in 2017 (commit [f786d2e660721a0238949e7abce20852879de8ef](https://github.com/joshwlewis/unitwise/commit/f786d2e660721a0238949e7abce20852879de8ef), 3 years ago) so I don't think this gem should be considered actively maintained any longer.

[doc] Update information about the unitwise gem in README

---

lib/measured/base.rb
lib/measured/conversion_table_builder.rb
lib/measured/missing_conversion_path.rb
lib/measured/unit_already_added.rb
lib/measured/unit_error.rb
lib/measured/unit_system_builder.rb
test/unit_system_builder_test.rb

This way, users of this library have more control on how to handle these errors, and provide their own custom error message.

Add structure to unit errors

---

measured.gemspec

Bumping version support to rails 5.2 because that's all that's supported officially.
https://guides.rubyonrails.org/maintenance_policy.html
Behaviour in old versions is undefined.
CI already matches this as of #134

Only support rails versions that are still supported, meaning 5.2 and above

---

CHANGELOG.md
lib/measured/version.rb

This is a tiny release:
https://github.com/Shopify/measured/compare/9047b7186e9168f0cbafaf80e34af4fbb881c2df...fd93dabe844f6a26272b9c7186ac63cbbc743141
It bumps dev ruby and drops support for ruby 2.5. I also renamed `master` to `main`.
Mostly it is to release https://github.com/Shopify/measured-rails/pull/67 and that gem is version locked to this one.

Release 2.8.0

---

README.md
lib/measured/measurable.rb
lib/measured/unit.rb
test/measurable_test.rb
test/unit_test.rb

Hi. #138 seemed like a reasonable request, so I tried to fulfill it.
I tried to follow existing conventions, but this is my first time looking at the repository, so I've probably missed something.

allow Measurable#format to drop the conversion string

---

lib/measured/measurable.rb

When instantiating a large volume of `Measurable` objects `gsub` is run indiscriminately. I'm adding a defensive check as benchmarks show this is a lot faster. 
<details>
<summary>bench.rb</summary>
```ruby
require "benchmark/ips"
class BenchGsub
VALUES = 1000.times.map { |v| (v / 10).to_s }
class << self
def raw
VALUES.each { |v| v.gsub(/\.0*\Z/, "") }
end
def check(value)
VALUES.each { |v| v.gsub(/\.0*\Z/, "") if /\.0*\Z/.match?(v) }
end
end
end
Benchmark.ips do |x|
x.report("raw", &BenchGsub.method(:raw))
x.report("check", &BenchGsub.method(:check))
x.compare!
end
```
</details>
```Warming up --------------------------------------
raw    71.000 i/100ms
check   432.286B i/100ms
Calculating -------------------------------------
raw      3.405k (± 4.1%) i/s -     17.040k in   5.015206s …
```

Add defensive check to avoid unnecessary gsub
